spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_voucher
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: phuocthuan2003@gmail.com
    password: kvxrsejjgvqhbidv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s

app:
  rate-limit:
    default-per-minute: 100
  email:
    verification-expiry-hours: 24
    reset-token-expiry-hours: 1
  base-url: http://localhost:8080
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

logging:
  level:
    com.smartvoucher: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
